/* Published site customisation (theme + screen layouts).
 * Generated by the System area on 14 August 2026.
 * Commit this file to the repo root as customisation.js to apply it for everyone. */
window.FMC_CUSTOM = {
  "theme": {
    "colors": {
      "brand": "#0B132B",
      "brandDeep": "#0F172A",
      "accent": "#0284C7",
      "paper": "#F8FAFC",
      "surface": "#FFFFFF",
      "ink": "#0F172A",
      "inkSoft": "#64748B"
    },
    "fonts": {
      "display": "Bricolage Grotesque",
      "body": "Public Sans"
    },
    "styles": {
      "headingWeight": 700,
      "baseSize": 15,
      "headingSpacing": -0.01,
      "radius": 16
    }
  },
  "layouts": {}
};
