/* Published site customisation (theme + screen layouts).
 * Generated by System → Theme Studio / Screen Layouts → "Publish".
 * Replace this file's contents with the downloaded one and commit.
 * null = use the built-in defaults. */
window.FMC_CUSTOM = null;
